import { Router } from "express";
import { sendSuccess } from "../common/helpers/send-success.js";
import { authenticateAdmin } from "../common/middleware/authenticate-admin.js";
import { authRouter } from "../modules/auth/auth.routes.js";
import {adminBookingRouter, publicBookingRouter,} from "../modules/bookings/booking.routes.js";
export const apiRouter = Router();
apiRouter.get("/health", (_req, res) => sendSuccess(res, { status: "ok" }, "API is healthy"));
apiRouter.use("/auth", authRouter);
apiRouter.use("/bookings", publicBookingRouter);
apiRouter.use("/admin/bookings", authenticateAdmin, adminBookingRouter);
